// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_RESTAURANTE_DATOS;

#nullable disable

namespace WEB_RESTAURANTE_DATOS.Migrations
{
    [DbContext(typeof(AplicacionContexto))]
    [Migration("20251221220021_septimo")]
    partial class septimo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_RESTAURANTE_DATOS.Entidades.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Destino3")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Destino4")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("WEB_RESTAURANTE_DATOS.Entidades.Usuarios", b =>
                {
                    b.Property<int>("idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idusuario"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Pasword")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("idcorrelativo")
                        .HasColumnType("int");

                    b.HasKey("idusuario");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
